from ...helpers.convert_to_ph_timezone import update_to_ph_datetime
from ...helpers.get_complete_name import get_complete_name

PatientVisitChargeCodes = {
    "_id": 0,
    "ChargeCodeDetailID": {"$ifNull": ["$chargecodes._id", ""]},
    "ChargeCodeID": "$_id",
    "OrgCode": {"$ifNull": [{"$arrayElemAt": ["$Organisation.code", 0]}, ""]},
    "MRN":  {"$ifNull": [{"$arrayElemAt": ["$Patient.mrn", 0]}, ""]},
    "PatientvisitID": {"$ifNull": [{"$arrayElemAt": ["$PatientVisit.visitid", 0]}, ""]},
    "OrderItemName": {"$ifNull": [{"$arrayElemAt": ["$OrderItem.name", 0]}, ""]},
    "OrderItemCode": {"$ifNull": [{"$arrayElemAt": ["$OrderItem.code", 0]}, ""]},
    "OrderToDeptCode": {"$ifNull": [{"$arrayElemAt": ["$OrderToDepartment.code", 0]}, ""]},
    "OrderToDeptName": {"$ifNull": [{"$arrayElemAt": ["$OrderToDepartment.name", 0]}, ""]},
    "BillingGroupName":  {"$ifNull": [{"$arrayElemAt": ["$BillingGroup.name", 0]}, ""]},
    "BillingGroupCode":  {"$ifNull": [{"$arrayElemAt": ["$BillingGroup.code", 0]}, ""]},
    "BillingSubGroupName":  {"$ifNull": [{"$arrayElemAt": ["$BillingSubGroup.name", 0]}, ""]},
    "BillingSubGroupCode":  {"$ifNull": [{"$arrayElemAt": ["$BillingSubGroup.code", 0]}, ""]},
    "TariffID": {"$ifNull": ["$chargecodes.tariffuid", ""]},
    "ChargeCodeType": {"$ifNull": ["$chargecodes.chargecodetype", ""]},
    "IsAutoChargeRule": {"$ifNull": ["$chargecodes.isautochargerule", ""]},
    "OrderNumber": {"$ifNull": ["$chargecodes.ordernumber", ""]},
    "PatientOrderID": {"$ifNull": ["$chargecodes.patientorderuid", ""]},
    "PatientOrderItemID": {"$ifNull": ["$chargecodes.patientorderitemuid", ""]},
    "Quantity": {"$ifNull": ["$chargecodes.quantity", ""]},
    "OriginalQuantity": {"$ifNull": ["$chargecodes.orgquantity", ""]},
    "BalanceQuantity": {"$ifNull": ["$chargecodes.balancequantity", ""]},
    "UnitPrice": {"$ifNull": ["$chargecodes.unitprice", ""]},
    "PayorDiscount": {"$ifNull": ["$chargecodes.payordiscount", ""]},
    "SpecialDiscount": {"$ifNull": ["$chargecodes.specialdiscount", ""]},
    "TaxAmount": {"$ifNull": ["$chargecodes.taxamount", ""]},
    "NetAmount": {"$ifNull": ["$chargecodes.netamount", ""]},
    "CostPrice": {"$ifNull": ["$chargecodes.costprice", ""]},
    "ChargeDate": update_to_ph_datetime("$chargecodes.chargedate"),
    "IsBilled": {"$ifNull": ["$chargecodes.isbilled", ""]},
    "PatientBillID": {"$ifNull": ["$chargecodes.patientbilluid", ""]},
    "StatusFlag": {"$ifNull": ["$statusflag", ""]},
    "CreatedByName": get_complete_name("$CreatedBy"),
    "CreatedByCode": {"$ifNull": [{"$arrayElemAt": ["$CreatedBy.code", 0]}, " "]},
    "CreatedAt": update_to_ph_datetime("$createdat"),
    "ModifiedByName": get_complete_name("$ModifiedBy"),
    "ModifiedByCode": {"$ifNull": [{"$arrayElemAt": ["$ModifiedBy.code", 0]}, " "]},
    "ModifiedAt": update_to_ph_datetime("$modifiedat"),
}
