# from ....utils.get_complete_name import get_complete_name
# from ....utils.update_to_ph_datetime import update_to_ph_datetime
from ...helpers.convert_to_ph_timezone import update_to_ph_datetime
from ...helpers.get_complete_name import get_complete_name

PatientVisitOrders = {
    "_id": 0,
    "PatientOrderItemID": {"$ifNull": ["$patientorderitems._id", None]},
    "PatientOrderID": "$_id",
    "OrgCode": {"$ifNull": [{"$arrayElemAt": ["$Organisation.code", 0]}, ""]},
    "MRN":  {"$ifNull": [{"$arrayElemAt": ["$Patient.mrn", 0]}, ""]},
    "PatientvisitID": {"$ifNull": [{"$arrayElemAt": ["$PatientVisit.visitid", 0]}, ""]},
    "PatientEncounterType": {"$ifNull": [{"$arrayElemAt": ["$EncounterType.valuedescription", 0]}, ""]},
    "ReturnedPatienOrderNumber": {"$ifNull": ["$patientorderitems.parentordernumber", None]},
    "ReturnedPatienOrderID": {"$ifNull": ["$patientorderitems.parentorderuid", None]},
    "ReturnedPatienOrderItemID": {"$ifNull": ["$patientorderitems.parentorderitemuid", None]},
    "OrderNumber": {"$ifNull": ["$ordernumber", 0]},
    "OrderedDate": update_to_ph_datetime("$orderdate"),
    "BillingGroupName":  {"$ifNull": [{"$arrayElemAt": ["$BillingGroup.name", 0]}, ""]},
    "BillingGroupCode":  {"$ifNull": [{"$arrayElemAt": ["$BillingGroup.code", 0]}, ""]},
    "BillingSubGroupName": {"$ifNull": [{"$arrayElemAt": ["$BillingSubGroup.name", 0]}, ""]},
    "BillingSubGroupCode":  {"$ifNull": [{"$arrayElemAt": ["$BillingGroup.code", 0]}, ""]},
    "OrderItemName": {"$ifNull": ["$patientorderitems.orderitemname", 0]},
    "OrderItemCode": {"$ifNull": [{"$arrayElemAt": ["$OrderItem.code", 0]}, ""]},
    "ChargeCode": {"$ifNull": ["$patientorderitems.chargecode", None]},
    "OrderCatType": {"$ifNull": ["$patientorderitems.ordercattype", 0]},
    "OrderSetName": {"$ifNull": [{"$arrayElemAt": ["$OrderSet.name", 0]}, ""]},
    "OrderSetCode": {"$ifNull": [{"$arrayElemAt": ["$OrderSet.code", 0]}, ""]},
    "OrderCat": {"$ifNull": [{"$arrayElemAt": ["$OrderCategory.name", 0]}, ""]},
    "OrderCatCode": {"$ifNull": [{"$arrayElemAt": ["$OrderCategory.code", 0]}, ""]},
    "OrderSubCat": {"$ifNull": [{"$arrayElemAt": ["$OrderSubCategory.name", 0]}, ""]},
    "OrderSubCatCode": {"$ifNull": [{"$arrayElemAt": ["$OrderSubCategory.code", 0]}, ""]},
    "Quantity": {"$ifNull": ["$patientorderitems.quantity", None]},
    "QuantityUOM": {"$ifNull": [{"$arrayElemAt": ["$QuantityUOM.valuedescription", 0]}, ""]},
    "QuantityUOMCode": {"$ifNull": [{"$arrayElemAt": ["$QuantityUOM.valuecode", 0]}, ""]},
    "UnitPrice": {"$ifNull": ["$patientorderitems.unitprice", None]},
    "TaxPercentage": {"$ifNull": ["$patientorderitems.taxpercentage", None]},
    "TaxAmount": {"$ifNull": ["$patientorderitems.taxamount", None]},
    "PayorDiscount": {"$ifNull": ["$patientorderitems.payordiscount", None]},
    "SpecialDiscount": {"$ifNull": ["$patientorderitems.specialdiscount", None]},
    "CostPrice": {"$ifNull": [{"$arrayElemAt": ["$Tariff.costprice", 0]}, ""]},
    "DoctorShare": {"$ifNull": [{"$arrayElemAt": ["$Tariff.doctorshare", 0]}, ""]},
    "CoPayAmount": {"$ifNull": ["$patientorderitems.copayamount", None]},
    "IsOTCSale": {"$ifNull": ["$patientorderitems.isotcsale", None]},
    "TotalPrice": {"$ifNull": ["$patientorderitems.totalprice", None]},
    "BatchNumber": {"$ifNull": ["$patientorderitems.batchid", None]},
    "LotNumber": {"$ifNull": ["$patientorderitems.internalbatchid", None]},
    "ExpiryDate": update_to_ph_datetime("$patientorderitems.expirydate"),
    "AccessionNumber": {"$ifNull": ["$patientorderitems.accessionnumber", None]},
    "SpecimenNumber": {"$ifNull": ["$patientorderitems.specimennumber", None]},
    "SpecimenCollectedDate": update_to_ph_datetime("$patientorderitems.specimencollectedat"),
    "CareProviderName": get_complete_name("$CareProvider"),
    "CareProviderCode": {"$ifNull": [{"$arrayElemAt": ["$CareProvider.code", 0]}, ""]},
    "Qualification": {"$ifNull": [{"$arrayElemAt": ["$CareProvider.qualification", 0]}, ""]},
    "LicenseNumber": {"$ifNull": [{"$arrayElemAt": ["$CareProvider.licensenumber", 0]}, ""]},
    "S2License": {"$ifNull": [{"$arrayElemAt": ["$CareProvider.bio", 0]}, ""]},
    "PTR": {"$ifNull": [{"$arrayElemAt": ["$CareProvider.gstregno", 0]}, ""]},
    "StatusDesc": {"$ifNull": [{"$arrayElemAt": ["$Status.valuedescription", 0]}, ""]},
    "StatusCode": {"$ifNull": [{"$arrayElemAt": ["$Status.valuecode", 0]}, ""]},
    "OrderDeptCode": {"$ifNull": [{"$arrayElemAt": ["$OrderDepartment.code", 0]}, ""]},
    "OrderDeptName": {"$ifNull": [{"$arrayElemAt": ["$OrderDepartment.name", 0]}, ""]},
    "OrderToDeptCode": {"$ifNull": [{"$arrayElemAt": ["$OrderToDepartment.code", 0]}, ""]},
    "OrderToDeptName": {"$ifNull": [{"$arrayElemAt": ["$OrderToDepartment.name", 0]}, ""]},
    "BedCat": {"$ifNull": [{"$arrayElemAt": ["$BedCat.valuecode", 0]}, ""]},
    "BedCatCode": {"$ifNull": [{"$arrayElemAt": ["$BedCat.valuedescription", 0]}, ""]},
    "Store": {"$ifNull": [{"$arrayElemAt": ["$Store.name", 0]}, ""]},
    "StoreCode": {"$ifNull": [{"$arrayElemAt": ["$Store.code", 0]}, ""]},
    "PatientPackageID": {"$ifNull": ["$patientorderitems.patientpackageuid", None]},
    "PatientPackageItemID": {"$ifNull": ["$patientorderitems.patientpackageitemuid", None]},
    "PatientFutureOrderID": {"$ifNull": ["$patientorderitems.patientfutureorderuid", None]},
    "TariffID": {"$ifNull": ["$patientorderitems.tariffuid", None]},
    "ExecutedDate": {"$ifNull": ["$patientorderitems.executedat", None]},
    "UpdatedDate": {"$ifNull": ["$patientorderitems.updatedAt", None]},
    "ResultAuthorizedDate": {"$ifNull": ["$patientorderitems.resultauthorizedat", None]},
    "CreatedByName": get_complete_name("$CreatedBy"),
    "CreatedByCode": {"$ifNull": [{"$arrayElemAt": ["$CreatedBy.code", 0]}, ""]},
    "CreatedAt": update_to_ph_datetime("$createdat"),
    "ModifiedByName": get_complete_name("$ModifiedBy"),
    "ModifiedByCode": {"$ifNull": [{"$arrayElemAt": ["$ModifiedBy.code", 0]}, ""]},
    "ModifiedAt": update_to_ph_datetime("$modifiedat"),
}
